spring:
  mvc:
    view:
      suffix: .html
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
      generate-ddl: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mariadb
    username: mariadb
    password: mariadb